#!/usr/bin/env bash

# -- php composer and php in open docker network --
WORKSPACE_NAME="a4dc_h523"

# -- php prod mode, php bound to internal docker network without internet --
# WORKSPACE_NAME="a4dc_h525"



SOFTWARE_NAMESPACE="jaisocx"
SOFTWARE_NAME="sites_docker_environment"
SOFTWARE_VERSION="1_2_0"
#; echo $PATH: /opt/jaisocx/sites_docker_environment/v1_2_0/node_v26.4.0/

WHETHER_DEV_MODE="true"



# -- VOLUMES --
WORKSPACE_VOLUME="./workspace"
IN_DOCKER_WORKSPACE_VOLUME="/opt/jaisocx/sites_docker_environment/workspace"
TYPESCRIPT_PACKAGES="ts/cloned_repos/jaisocx_sitestools"

# -- DOMAINS --
DOMAIN_NAME="basetasks.site"

FORBROWSER_NODE_DOMAIN_NAME="node.basetasks.site"
NODE_INTERNAL_DOMAIN_NAME="nodeinternal.basetasks.site"
NODE_OPENED_DOMAIN_NAME="nodeopened.basetasks.site"

FORBROWSER_EXPRESS_DOMAIN_NAME="express.basetasks.site"
EXPRESS_INTERNAL_DOMAIN_NAME="expressinternal.basetasks.site"
EXPRESS_OPENED_DOMAIN_NAME="expressopened.basetasks.site"


FORBROWSER_DOMAIN_NAME="local.basetasks.site"
JAISOCX_DOMAIN_NAME="dck.basetasks.site"
JAISOCX_OPENED_DOMAIN_NAME="opendck.basetasks.site"


PHP_FPM_OPEN_DOMAIN_NAME="fpmopen.basetasks.site"
PHP_FPM_DOMAIN_NAME="phpfpm.basetasks.site"
PHP_COMPOSER_DOMAIN_NAME="phpcomposer.basetasks.site"

# -- DNS --
DNS_SERVER_IPv4=8.8.8.8



# --------------
# -- NETWORKS --
# -- php composer and php in open docker network --
# WORKSPACE_NAME="a4dc_h523"
# -- php prod mode, php bound to internal docker network without internet --
# WORKSPACE_NAME="a4dc_h525"

# networks:
  # jaisocx_dc_opened_one_for_browsers_network:
OPENED_ONE_FOR_BROWSERS_NETWORK_NAME="jaisocx_dc_a4dc_h523_opened_one_for_browsers_network"
    # driver: bridge
  # jaisocx_dc_opened_for_inet_installs_network:
OPENED_FOR_INET_INSTALLS_NETWORK_NAME="jaisocx_dc_a4dc_h523_opened_for_inet_installs_network"
    # driver: bridge
  # jaisocx_dc_internal_connected_all_network:
INTERNAL_CONNECTED_ALL_NETWORK_NAME="jaisocx_dc_a4dc_h523_internal_connected_all_network"
    # driver: ipvlan



# -- subnets --
# -- php prod mode, php bound to internal docker network without internet --
# WORKSPACE_NAME="a4dc_h525"
#  OPENED_SUBNET_IPv4="172.20.250.0/24"
#  OPENED_IP_RANGE_IPv4="172.20.250.244/30"
#
#  OPENED_SUBNET_IPv6="fdae:f122:9df5:4::/64"
#  OPENED_IP_RANGE_IPv6="fdae:f122:9df5:4::/64"
#
#
#  SUBNET_IPv4="172.20.251.0/24"
#  IP_RANGE_IPv4="172.20.251.224/27"
#
#  SUBNET_IPv6="fdae:f122:9df5:5::/64"
#  IP_RANGE_IPv6="fdae:f122:9df5:5::/64"


# -- php composer and php in open docker network --
# WORKSPACE_NAME="a4dc_h523"
OPENED_SUBNET_IPv4="172.21.252.0/24"
OPENED_IP_RANGE_IPv4="172.21.252.244/30"

OPENED_SUBNET_IPv6="fdae:f122:9dea:a::/64"
OPENED_IP_RANGE_IPv6="fdae:f122:9dea:a::/64"


SUBNET_IPv4="172.20.253.0/24"
IP_RANGE_IPv4="172.20.253.224/27"

SUBNET_IPv6="fdae:f122:9dea:9::/64"
IP_RANGE_IPv6="fdae:f122:9dea:9::/64"



# -- ip addresses --
# -- php prod mode, php bound to internal docker network without internet --
# WORKSPACE_NAME="a4dc_h525"
#  A4DC_IPv6="fdae:f122:9df5:5::2"
#  A4DC_IPv4="172.20.251.225"
#
#  OPENED_JAISOCX_HTTP_IPv6="fdae:f122:9df5:4::3"
#  OPENED_JAISOCX_HTTP_IPv4="172.20.250.245"
#
#  NODE_IPv4="172.20.251.229"
#
#  JAISOCX_HTTP_IPv6="fdae:f122:9df5:5::3"
#  JAISOCX_HTTP_IPv4="172.20.251.226"
#
#  PHP_FPM_IPv6="fdae:f122:9df5:5::4"
#  PHP_FPM_IPv4="172.20.251.227"
#
#  PHP_COMPOSER_IPv6="fdae:f122:9df5:5::5"
#  PHP_COMPOSER_IPv4="172.20.251.228"



# -- php composer and php in open docker network --
# WORKSPACE_NAME="a4dc_h523"
A4DC_IPv6="fdae:f122:9dea:9::2"
A4DC_IPv4="172.20.253.225"

OPENED_JAISOCX_HTTP_IPv6="fdae:f122:9dea:a::3"
OPENED_JAISOCX_HTTP_IPv4="172.21.252.245"

NODE_IPv4="172.20.253.229"
NODE_IPv6="fdae:f122:9dea:9::9"

JAISOCX_HTTP_IPv6="fdae:f122:9dea:9::3"
JAISOCX_HTTP_IPv4="172.20.253.226"

PHP_FPM_IPv6="fdae:f122:9dea:9::4"
PHP_FPM_IPv4="172.20.253.227"

PHP_COMPOSER_IPv6="fdae:f122:9dea:9::5"
PHP_COMPOSER_IPv4="172.20.253.228"



# -- ports --
JAISOCX_HTTP_FLAT_PORT=2297
JAISOCX_HTTPS_PORT=8447

PHP_FPM_FLAT_PORT=9020
PHP_FPM_STATUS_PORT=9022
PHP_XDEBUG_FLAT_PORT=9050

### THIS CONF BLOCK WITH HTTP PORTS DOESN'T DO AUTOMATIQUE,
### SINCE 1. DOCKERFILE EXPOSE PORT NUMBER IS HARDCODED,
###   2. AND DOCKER-COMPOSE.YML STANDARD PORTS MAPPINGS HAVE TO BE HARDCODED TO BE ABLE TO SEE
###   3. AND SEVERAL OTHER TASKS, AND EXPRESS AND NODE_HTTPS START package.json:script EITHER
###   4. MOREOVER, FOR .env TO TAKE EFFECT WITH PORTS, SINCE IN EXPOSE INSTRUCTIONS IN DOCKERFILE, NEW DOCKER BUILD IS REQUIRED, NOT JUST RESTART.
### Sets here slowly NODE HTTP SERVICES PORTS thinking on ports opened and their amount.
# NODE_HTTP_FLAT_PORT=80
# NODE_HTTPS_PORT=443
NODE_HTTP_FLAT_PORT=8085
NODE_HTTPS_PORT=8445
### EXPRESS_PORT is in js hardcoded
EXPRESS_SECURE_PORT=9443
EXPRESS_PORT=3000
NODE_DEBUG_PORT=9229



A4DC_INSTALL_TARBALLS_VOLUME="./docker_compose/Prince/tarballs"
A4DC_INSTALL_IN_DOCKER_TARBALLS_VOLUME="/tarballs"

PHP_TARBALLS_VOLUME="./docker_compose/PHP/tarballs"
PHP_TARBALLS_IN_DOCKER_VOLUME="/tarballs"

NODE_TARBALLS_VOLUME="./docker_compose/ts/tarballs"
NODE_TARBALLS_IN_DOCKER_VOLUME="/tarballs"



# -- SITES SERVER --
SOFTWARE_HOME="/opt/jaisocx/sites_docker_environment/v1_2_0/soft_home"
LOGS_HOME="/opt/jaisocx/sites_docker_environment/v1_2_0/logs"

A4DC_SOFTWARE_HOME="/opt/jaisocx/sites_docker_environment/v1_2_0/soft_home/prince/v16_2"
JAISOCX_SOFTWARE_HOME="/opt/jaisocx/sites_docker_environment/v1_2_0/soft_home/jaisocx/v3_0_16/jaisocx-http"
NODE_SOFTWARE_HOME="/opt/jaisocx/sites_docker_environment/v1_2_0/soft_home/node/v24_11_0"
PHP_SOFTWARE_HOME="/opt/jaisocx/sites_docker_environment/v1_2_0/soft_home/php/v8_3"

A4DC_SOFTWARE_LOGS="/opt/jaisocx/sites_docker_environment/v1_2_0/logs/prince"
JAISOCX_SOFTWARE_LOGS="/opt/jaisocx/sites_docker_environment/v1_2_0/soft_home/jaisocx/v3_0_16/jaisocx-http/logs"
NODE_SOFTWARE_LOGS="/opt/jaisocx/sites_docker_environment/v1_2_0/logs/node"
PHP_SOFTWARE_LOGS="/opt/jaisocx/sites_docker_environment/v1_2_0/logs/php"


