#!/usr/bin/env bash

WORKSPACE_NAME="a4dc_h524"

WHETHER_DEV_MODE="true"



# -- VOLUMES --
WORKSPACE_VOLUME="./workspace"
IN_DOCKER_WORKSPACE_VOLUME="/opt/jaisocx/a4dc/workspace"

# -- DOMAINS --
DOMAIN_NAME="basetasks.site"

FORBROWSER_DOMAIN_NAME="local.basetasks.site"
JAISOCX_DOMAIN_NAME="dck.basetasks.site"
JAISOCX_OPENED_DOMAIN_NAME="opendck.basetasks.site"

PHP_FPM_OPEN_DOMAIN_NAME="fpmopen.basetasks.site"
PHP_FPM_DOMAIN_NAME="fpm.basetasks.site"
PHP_COMPOSER_DOMAIN_NAME="phpcomposer.basetasks.site"

# -- DNS --
DNS_SERVER_IPv4=8.8.8.8


# --------------
# -- NETWORKS --
# networks:
  # jaisocx_dc_opened_one_for_browsers_network:
OPENED_ONE_FOR_BROWSERS_NETWORK_NAME="jaisocx_dc_a4dc_h524_opened_one_for_browsers_network"
    # driver: bridge
  # jaisocx_dc_opened_for_inet_installs_network:
OPENED_FOR_INET_INSTALLS_NETWORK_NAME="jaisocx_dc_a4dc_h524_opened_for_inet_installs_network"
    # driver: bridge
  # jaisocx_dc_internal_connected_all_network:
INTERNAL_CONNECTED_ALL_NETWORK_NAME="jaisocx_dc_a4dc_h524_internal_connected_all_network"
    # driver: ipvlan



# -- subnets --
OPENED_SUBNET_IPv6="fdae:f122:9df5:4::/64"
OPENED_IP_RANGE_IPv6="fdae:f122:9df5:4::/64"

OPENED_SUBNET_IPv4="172.20.250.0/24"
OPENED_IP_RANGE_IPv4="172.20.250.244/30"


SUBNET_IPv6="fdae:f122:9df5:5::/64"
IP_RANGE_IPv6="fdae:f122:9df5:5::/64"

SUBNET_IPv4="172.20.251.0/24"
IP_RANGE_IPv4="172.20.251.224/27"


# -- ip addresses --
A4DC_IPv6="fdae:f122:9df5:5::2"
A4DC_IPv4="172.20.251.225"

OPENED_JAISOCX_HTTP_IPv6="fdae:f122:9df5:4::3"
OPENED_JAISOCX_HTTP_IPv4="172.20.250.245"

JAISOCX_HTTP_IPv6="fdae:f122:9df5:5::3"
JAISOCX_HTTP_IPv4="172.20.251.226"

PHP_FPM_IPv6="fdae:f122:9df5:5::4"
PHP_FPM_IPv4="172.20.251.227"

PHP_COMPOSER_IPv6="fdae:f122:9df5:5::5"
PHP_COMPOSER_IPv4="172.20.251.228"


# -- ports --
JAISOCX_HTTP_FLAT_PORT=2297
JAISOCX_HTTPS_PORT=8447

PHP_FPM_FLAT_PORT=9020
PHP_FPM_STATUS_PORT=9022
PHP_XDEBUG_FLAT_PORT=9050


A4DC_INSTALL_TARBALLS_VOLUME="./docker_compose/Prince/tarballs"
A4DC_INSTALL_IN_DOCKER_TARBALLS_VOLUME="/tarballs"

PHP_TARBALLS_VOLUME="./docker_compose/PHP/tarballs"
PHP_TARBALLS_IN_DOCKER_VOLUME="/tarballs"


# -- SITES SERVER --
SOFTWARE_NAMESPACE="jaisocx"
SOFTWARE_NAME="a4_dc"
SOFTWARE_VERSION="1.0.1"
SOFTWARE_HOME="/opt/jaisocx/a4dc/v1_0_1/soft_home"
LOGS_HOME="/opt/jaisocx/a4dc/v1_0_1/logs"

A4DC_SOFTWARE_HOME="/opt/jaisocx/a4dc/v1_0_1/soft_home/prince/v16_2"
JAISOCX_SOFTWARE_HOME="/opt/jaisocx/a4dc/v1_0_1/soft_home/jaisocx/v3_0_16/jaisocx-http"
NODE_SOFTWARE_HOME="/opt/jaisocx/a4dc/v1_0_1/soft_home/node/v24_11_0"
PHP_SOFTWARE_HOME="/opt/jaisocx/a4dc/v1_0_1/soft_home/php/v8_3"

A4DC_SOFTWARE_LOGS="/opt/jaisocx/a4dc/v1_0_1/logs/prince"
JAISOCX_SOFTWARE_LOGS="/opt/jaisocx/a4dc/v1_0_1/soft_home/jaisocx/v3_0_16/jaisocx-http/logs"
NODE_SOFTWARE_LOGS="/opt/jaisocx/a4dc/v1_0_1/logs/node"
PHP_SOFTWARE_LOGS="/opt/jaisocx/a4dc/v1_0_1/logs/php"


