#!/bin/bash

TIME_ZONE="Europe/Paris"

SHELL="/bin/bash"

# -- CPU --
# Intel: x86_64 |  Apple MacBook: aarch64
# CPU_ARCHITECTURE_A4DC="x86_64"
CPU_ARCHITECTURE_A4DC="aarch64"

# AMD: amd64 | Apple MacBook: mac
CPU_ARCHITECTURE_JAISOCX="mac"



A4DC_SOFTWARE_VERSION="16.2"
JAISOCX_SOFTWARE_VERSION="3.0.16"
PHP_SOFTWARE_VERSION="8.3"
NODE_SOFTWARE_VERSION="24.11.0"



PROJECT_VOLUME="./workspace/ts"
IN_DOCKER_WORKSPACE_VOLUME="/opt/jaisocx/sites_docker_environment/workspace/ts"
YARN_HOME="/opt/jaisocx/sites_docker_environment/workspace/ts/build_tools/command/tsvm/yarn"



A4DC_SOFTWARE_LATEST_LTS="16.2"
A4DC_SOFTWARE_LATEST_RELEASE="16.2"

JAISOCX_SOFTWARE_LATEST_LTS="3.0.16"
JAISOCX_SOFTWARE_LATEST_RELEASE="3.0.16"

PHP_SOFTWARE_LATEST_LTS="8.5"
PHP_SOFTWARE_LATEST_RELEASE="8.5"

NODE_LATEST_LTS="24.16.0"
NODE_LATEST_RELEASE="26.3.0"



# -- USERS' GROUPS, USERS --
# -- groups --
GROUP_SUDIER_NAME=admin
GROUP_SUDIER_ID=1002
ADD_SUDIERS="true"

GROUP_A4DC_NAME=prince
GROUP_A4DC_ID=2325

GROUP_JAISOCX_NAME=jaisocx
GROUP_JAISOCX_ID=2524

GROUP_JAVA_NAME=java
GROUP_JAVA_ID=2525

GROUP_PHP_NAME=php
GROUP_PHP_ID=2330

GROUP_NODE_NAME=node
GROUP_NODE_ID=2329

GROUP_USERS_NAME=privileged
GROUP_USERS_ID=3435

GROUP_READER_NAME=reader
GROUP_READER_ID=3535



# -- mkpasswd --
# mkpasswd -m des asd

# -- users --
ROOT_HASHED_PWD="q6DDn07ExN73M"

USER_SUDIER_NAME=admin
USER_SUDIER_ID=1205
USER_SUDIER_HASHED_PWD="q6DDn07ExN73M"

USER_JAISOCX_NAME=jaisocx
USER_JAISOCX_ID=2120
USER_JAISOCX_HASHED_PWD="q6DDn07ExN73M"

USER_JAVA_NAME=java
USER_JAVA_ID=2202
USER_JAVA_HASHED_PWD="q6DDn07ExN73M"

USER_A4DC_NAME=prince
USER_A4DC_ID=2532
USER_A4DC_HASHED_PWD="q6DDn07ExN73M"

USER_PHP_NAME=php
USER_PHP_ID=3024
USER_PHP_HASHED_PWD="q6DDn07ExN73M"

USER_NODE_NAME=node
USER_NODE_ID=3025
USER_NODE_HASHED_PWD="q6DDn07ExN73M"

USER_NAME=user
USER_ID=3030
USER_HASHED_PWD="q6DDn07ExN73M"

USER_NPX_NAME=npx
USER_NPX_ID=5352
USER_NPX_HASHED_PWD="q6DDn07ExN73M"

USER_NPM_NAME=npm
USER_NPM_ID=5353
USER_NPM_HASHED_PWD="q6DDn07ExN73M"

USER_PNPM_NAME=pnpm
USER_PNPM_ID=5354
USER_PNPM_HASHED_PWD="q6DDn07ExN73M"

USER_YARN_NAME=yarn
USER_YARN_ID=5355
USER_YARN_HASHED_PWD="q6DDn07ExN73M"

USER_READER_NAME=reader
USER_READER_ID=1010
USER_READER_HASHED_PWD="q6DDn07ExN73M"



# ---------
# -- a4dc --
A4DC_INSTALL_TARBALL_RELOAD=false
A4DC_INSTALL_FOLDER="/dockr/a4dc/16_2"


# -- SITES SERVER --
JAVA_DC_JAISOCX_RAM_START="20m"
JAVA_DC_JAISOCX_RAM_MAXIMAL="300m"

PHP_FPM_HOST="${PHP_FPM_DOMAIN_NAME}:${PHP_FPM_FLAT_PORT}"



# -- PHP FPM --
PHP_FPM_LISTEN_MODE=750
# php-fpm.conf
#   log_level="${PHP_LOG_LEVEL}": degug | notice | warning | error
PHP_FPM_LOG_LEVEL=notice

# -- PHP --
PHP_LOG_LEVEL=E_NOTICE



### THIS CONF BLOCK WITH HTTP PORTS DOESN'T DO AUTOMATIQUE,
### SINCE 1. DOCKERFILE EXPOSE PORT NUMBER IS HARDCODED,
###   2. AND DOCKER-COMPOSE.YML STANDARD PORTS MAPPINGS HAVE TO BE HARDCODED TO BE ABLE TO SEE
###   3. AND SEVERAL OTHER TASKS, AND EXPRESS AND NODE_HTTPS START package.json:script EITHER
###   4. MOREOVER, FOR .env TO TAKE EFFECT WITH PORTS, SINCE IN EXPOSE INSTRUCTIONS IN DOCKERFILE, NEW DOCKER BUILD IS REQUIRED, NOT JUST RESTART.
### Sets here slowly NODE HTTP SERVICES PORTS thinking on ports opened and their amount.
# NODE_HTTP_FLAT_PORT=80
# NODE_HTTPS_PORT=443
NODE_HTTP_FLAT_PORT=8085
NODE_HTTPS_PORT=8445
### EXPRESS_PORT is in js hardcoded
EXPRESS_SECURE_PORT=9443
EXPRESS_PORT=3000
NODE_DEBUG_PORT=9229



### Force custom compatible npm ver. install
NPM_VER_FORCE_INSTALL=true
YARN_INSTALL=false

### npm, pnpm or yarn. but for now works just npm
PROJECT_NODE_PACKAGE_MANAGER=npm

### if set "true", then the tarball with node install loads from Inet every time on docker compose build and docker compose up.
### if set "false", proves automatique, whether the tarball already there, if not, then loads from Inet and stores in folder
### workspace/ts/build_tools/command/tsvm/tarballs
### this folder is in .gitignore file, and the saved tarballs are not pushed to GitHub,
### even when You publish Your own copy of this Alpine Image on Your GitServer.
NODE_INSTALL_TARBALL_RELOAD=false



### NodeJS ver. being installed for the "ts" dockerized NodeJS service
### for programming in TypeScript Programming Language,
### and to run ServerSide Scripts for Sites in NodeJS Programming Language
### on Express flat http endpoint on port 3000
NODE_VERSION="24.11.0"
NPM_VERSION="11.7.0"
YARN_VERSION="4.12.0-dev"



### LTS Long Time Support ver. number, LTS of some software sometimes being supported for 5 years even.
### Support means, the Software Manufacturing Company looks other software libs whether compatible, and runs tests from time to time,
### and doesn't erase the tarball to install from Inet.
# 22. December 2025
NODE_LATEST_LTS="24.16.0"
NODE_LATEST_RELEASE="26.3.0"



# the Typescript ProjectBuilder setting,
# ESNext is for running ProjectBuilder with a later node ver.,
# and CommonJS on the machines with the earlier node ver. installed.
# this variable sets, what ProjectBuilder compiled version will be called.
# ESNext is preferred, when You have the Node version 23.3 and above, since this ESNext build was done with Node v23.3.0
tsconfigVersion="ESNext"
tsServicePathCdn="/opt/jaisocx/sites_docker_environment/workspace/ts/cdn"

# the constants for the docker compose and the ProjectBuilder used with buildPacks.sh
# buildPacks.sh is to build the node projects, written in ts and js.

# docker-compose.yml ts service:
  # ts:
  #   build:
  #     context: ./docker/ts
  #   volumes:
  #     - ./workspace/ts/:/opt/jaisocx/sites_docker_environment/workspace/ts/
  #   volumes:
  #     - "${relativeProjectPathWithTsCode}:${tsServicePathInDockerVolume}"


