[XDEBUG]
zend_extension=xdebug.so

# Xdebug configuration
xdebug.mode=debug,develop,coverage,gcstats,trace,profile
xdebug.start_with_request=yes
xdebug.client_host=host.docker.internal
xdebug.client_port=9050
# this setting doesn't work with a variable: xdebug.client_port=$PHP_XDEBUG_FLAT_PORT
# -- TRY OUT WHETHER DYNAMIC ENV WORKS --
# .env: workspace/env_dc_dinamique/.env_php
# xdebug.client_port=$dyn_xdebug_client_port
xdebug.idekey=VSCODE

# for profiler and others
xdebug.output_dir="/opt/jaisocx/a4dc/v1_0_1/logs/php/xdebug/"


xdebug.trace_format=1  ; (1 = human-readable, 0 = compressed)
# xdebug.trace_output_dir="${PHP_SOFTWARE_LOGS}/xdebug/trace/"
# xdebug.trace_output_dir="/opt/jaisocx/a4dc/v1_0_1/logs/php/xdebug/trace/"
xdebug.trace_output_name="trace.%p"

xdebug.gc_stats.enable=1
# xdebug.gc_stats.output_dir="${PHP_SOFTWARE_LOGS}/xdebug/gc_stats/"
# xdebug.gc_stats.output_dir="/opt/jaisocx/a4dc/v1_0_1/logs/php/xdebug/gc_stats/"
xdebug.gc_stats.output_name="gcstats.%p"

# xdebug.profiler_output_dir="${PHP_SOFTWARE_LOGS}/xdebug/profiler/"
# xdebug.profiler_output_dir="/opt/jaisocx/a4dc/v1_0_1/logs/php/xdebug/profiler/"
xdebug.profiler_output_name="cachegrind.out.%p"

xdebug.show_error_trace=On
xdebug.show_exception_trace=On
xdebug.show_local_vars=On
xdebug.log_level=10
# xdebug.log="${PHP_SOFTWARE_LOGS}/xdebug/dbg/php83_xdebug.log"
xdebug.log="/opt/jaisocx/a4dc/v1_0_1/logs/php/xdebug/dbg/php83_xdebug.log"


